services:
  postgres:
    image: postgres:16
    container_name: movies-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - postgresql_initdb_data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a6a69c9927e948cf8f38335db9f4000f
    networks: 
      - movies-network
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: movies-pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=b9de630c8c7b42afbfdc533120f35b31
    networks:
      -  movies-network
    restart: always

  elastic:
    image: elasticsearch:8.15.2
    container_name: movies-elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      -  movies-network
    restart: always

  redis:
    image: redis:7.4.0
    container_name: movies-redis
    ports:
        - "6379:6379"
    volumes:
        - redis_data:/data/
    command: redis-server --databases 2
    networks:
      -  movies-network
    restart: always

  nginx:
    image: nginx:1.27.1
    container_name: movies-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    networks:
      -  movies-network
    restart: always

  kafka:
    image: bitnami/kafka:latest
    container_name: movies-kafka
    ports:
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami/kafka/data
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=7a308b458a504fb5bf17a3197da68222
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    networks:
      - movies-network
    restart: always

volumes:
  kafka_data:
    name: kafka_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./kafka/data
  postgresql_data:
    name: postgresql_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgresql/data
  postgresql_initdb_data:
    name: postgresql_initdb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgresql/initdb
  elasticsearch_data:
    name: elasticsearch_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./elasticsearch/data
  pgadmin_data:
    name: pgadmin_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pgadmin/data
  redis_data:
    name: redis_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./redis/data

networks:
  movies-network:
    name: movies-network
